/**
 * Errors generated by the API
 */
export default class ApiError {
  /**
   * @param {String} type - Error type
   * @param {String} message - Error message
   * @param {Number} code - Http error code
   */
  constructor(type, message, code) {
    this._type = type;
    this._message = message;
    this._code = code;
  }

  /**
   * Error type
   * @returns {String} - Error type
   */
  get type() {
    return this._type;
  }

  /**
   * Error message
   * @returns {String} - Error message
   */
  get message() {
    return this._message;
  }

  /**
   * Http error code
   * @returns {Number} - Http error code
   */
  get code() {
    return this._code;
  }

  /**
   * Display-able string
   * @returns {string} - Displayable error string
   */
  toString() {
    return `[${this._code}] ${this._type}: ${this._message}`;
  }
}
